DROP DATABASE Universidad;

#Se crea si no existe
CREATE DATABASE Universidad;

USE Universidad;

DROP TABLE Donador;

CREATE TABLE Usuarios (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(40),
  Contrasena VARCHAR(40)
);

CREATE TABLE Donador (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(40),
  Direccion VARCHAR(50),
  Telefono VARCHAR(20),
  Categoria VARCHAR(50),
  AnioGraduacion VARCHAR(10),
  MetodoPago VARCHAR(50)
);

CREATE TABLE Evento (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(50),
  Fecha DATE,
  Descripcion VARCHAR(100)
);

CREATE TABLE Donativo (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Donante_ID INT,
  Evento_ID INT,
  CantidadGarantizada DECIMAL(10,2),
  CantidadEnviada DECIMAL(10,2),
  FechaGarantia DATE,
  NumeroPagos INT,
  TarjetaCredito VARCHAR(16),
  CorporacionEmisora VARCHAR(40),
  DireccionCorporacion VARCHAR(60),
  NombreConyugue VARCHAR (40),
  FOREIGN KEY (Donante_ID) REFERENCES Donador(ID)  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Evento_ID) REFERENCES Evento(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CirculoDonadores(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NombreCirculo VARCHAR(30),
  CantidadMinima DECIMAL(10,2),
  CantidadMaxima DECIMAL(10,2)
);

CREATE TABLE Reportes(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Donante_ID INT,
  Donacion_ID INT,
  CirculoDonadores_ID INT,
  FOREIGN KEY (Donante_ID) REFERENCES Donador(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Donacion_ID) REFERENCES Donativo(ID)  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (CirculoDonadores_ID) REFERENCES CirculoDonadores(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RepresentanteClase(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NombreRepresentante VARCHAR(50)
);

CREATE TABLE ContactoClase(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Representante_ID INT,
  Donante_ID INT,
  Donacion_ID INT,
  FOREIGN KEY (Representante_ID) REFERENCES RepresentanteClase(ID)  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Donante_ID) REFERENCES Donador(ID)  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Donacion_ID) REFERENCES Donativo(ID)  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ContactoFonoton(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Evento_ID INT,
  Donante_ID INT,
  Donacion_ID INT,
  FOREIGN KEY (Evento_ID) REFERENCES Evento(ID)  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Donante_ID) REFERENCES Donador(ID)  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Donacion_ID) REFERENCES Donativo(ID)  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE AsistenciaEvento(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Evento_ID INT,
  Donante_ID INT,
  Donacion_ID INT,
  FOREIGN KEY (Evento_ID) REFERENCES Evento(ID)  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Donante_ID) REFERENCES Donador(ID)  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Donacion_ID) REFERENCES Donativo(ID)  ON DELETE CASCADE ON UPDATE CASCADE
);







